databases:
  - name: liftoff-postgres
    databaseName: liftoff_db
    plan: free
  - name: liftoff-redis
    plan: free

services:
  - type: web
    name: api-gateway
    plan: free
    autoDeploy: true
    healthCheck:
      path: /health
    dockerfilePath: ./apps/api-gateway/Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: API_KEY
        value: "your-strong-production-api-key-here"
      - fromService:
          type: web
          name: tenant-service
          envVarKey: TENANT_SERVICE_URL
      - fromDatabase:
          name: liftoff-redis
          property: connectionString
        key: REDIS_URL

  - type: web
    name: tenant-service
    plan: free
    autoDeploy: true
    healthCheck:
      path: /health
    internalPort: 3001
    dockerfilePath: ./apps/tenant-service/Dockerfile
    dockerContext: .
    envVars:
      - fromDatabase:
          name: liftoff-postgres
          property: connectionString
        key: DATABASE_URL
      - key: AMQP_URL
        value: "amqps://vqfrwqmw:dqOpui_y6M02B-HNpDjNA1994Xl7WH9b@moose.rmq.cloudamqp.com/vqfrwqmw"
      - fromDatabase:
          name: liftoff-redis
          property: connectionString
        key: REDIS_URL

  - type: worker
    name: db-provisioner-service
    plan: free
    autoDeploy: true
    dockerfilePath: ./apps/db-provisioner-service/Dockerfile
    dockerContext: .
    envVars:
      - fromDatabase:
          name: liftoff-postgres
          property: connectionString
        key: DATABASE_URL
      - key: AMQP_URL
        value: "amqps://vqfrwqmw:dqOpui_y6M02B-HNpDjNA1994Xl7WH9b@moose.rmq.cloudamqp.com/vqfrwqmw"

  - type: worker
    name: dns-provisioner-service
    plan: free
    autoDeploy: true
    dockerfilePath: ./apps/dns-provisioner-service/Dockerfile
    dockerContext: .
    envVars:
      - key: AMQP_URL
        value: "amqps://vqfrwqmw:dqOpui_y6M02B-HNpDjNA1994Xl7WH9b@moose.rmq.cloudamqp.com/vqfrwqmw"

  - type: worker
    name: credentials-service
    plan: free
    autoDeploy: true
    dockerfilePath: ./apps/credentials-service/Dockerfile
    dockerContext: .
    envVars:
      - fromDatabase:
          name: liftoff-postgres
          property: connectionString
        key: DATABASE_URL
      - key: AMQP_URL
        value: "amqps://vqfrwqmw:dqOpui_y6M02B-HNpDjNA1994Xl7WH9b@moose.rmq.cloudamqp.com/vqfrwqmw"

  - type: worker
    name: billing-service
    plan: free
    autoDeploy: true
    dockerfilePath: ./apps/billing-service/Dockerfile
    dockerContext: .
    envVars:
      - key: AMQP_URL
        value: "amqps://vqfrwqmw:dqOpui_y6M02B-HNpDjNA1994Xl7WH9b@moose.rmq.cloudamqp.com/vqfrwqmw"

  - type: worker
    name: notification-service
    plan: free
    autoDeploy: true
    dockerfilePath: ./apps/notification-service/Dockerfile
    dockerContext: .
    envVars:
      - key: AMQP_URL
        value: "amqps://vqfrwqmw:dqOpui_y6M02B-HNpDjNA1994Xl7WH9b@moose.rmq.cloudamqp.com/vqfrwqmw"